import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { EntityFilters, EntityType, RelationVerb } from '../../utils/types';
import {
  AgentEntity,
  AgentGraphDocument,
  AgentGraphEntityInput,
  AgentGraphEvidence,
  AgentGraphGroupInput,
  AgentGraphGroupKind,
  AgentGraphRelationInput,
  AgentGraphSnapshot,
  AgentGraphStats,
  AgentRelation,
} from './types';
import type { AgentEntityDescriptionOverrideStore } from './agentEntityOverrideService';

const ENTITY_TYPES = new Set<EntityType>([
  'function',
  'class',
  'interface',
  'variable',
  'file',
  'directory',
  'api',
  'config',
  'database',
  'service',
  'component',
  'external',
  'other',
]);

const RELATION_VERBS = new Set<RelationVerb>([
  'uses',
  'calls',
  'extends',
  'implements',
  'depends_on',
  'contains',
  'references',
  'imports',
  'exports',
]);

const GROUP_KINDS = new Set<AgentGraphGroupKind>([
  'framework',
  'module',
  'feature',
]);

const EMPTY_SNAPSHOT: AgentGraphSnapshot = {
  groups: [],
  entities: [],
  relations: [],
};

/**
 * Reads the declarative, grouped graph generated by an Agent Skill.
 *
 * Version 2 keeps independent framework/module/feature graphs in one sidecar.
 * Version 1 remains readable and is exposed as one framework group so existing
 * workspaces keep working until an Agent migrates their manifest.
 */
export class AgentGraphService {
  private readonly graphPath: string;
  private cachedSignature = '';
  private cachedSnapshot: AgentGraphSnapshot = EMPTY_SNAPSHOT;
  private lastError: Error | undefined;

  constructor(
    workspaceRoot: string,
    private readonly descriptionOverrides?: AgentEntityDescriptionOverrideStore
  ) {
    this.graphPath = path.join(
      workspaceRoot,
      '.vscode',
      '.knowledge',
      'agent-graph.json'
    );
  }

  public getGraphPath(): string {
    return this.graphPath;
  }

  public getLastError(): Error | undefined {
    this.load();
    return this.lastError;
  }

  public refresh(): void {
    this.cachedSignature = '';
    this.load();
  }

  public getSnapshot(): AgentGraphSnapshot {
    return this.load();
  }

  public listGroups(): AgentGraphSnapshot['groups'] {
    return this.load().groups;
  }

  public listEntities(filters?: EntityFilters): AgentEntity[] {
    return this.load().entities.filter((entity) => {
      if (filters?.type && entity.type !== filters.type) {
        return false;
      }
      if (filters?.filePath && entity.filePath !== filters.filePath) {
        return false;
      }
      if (
        filters?.name &&
        !entity.name.toLocaleLowerCase().includes(filters.name.toLocaleLowerCase())
      ) {
        return false;
      }
      return true;
    });
  }

  public getEntity(entityId: string): AgentEntity | null {
    return this.load().entities.find((entity) => entity.id === entityId) || null;
  }

  /** Save human prose by stable symbol key so it applies in every group. */
  public setManualDescription(
    entityId: string,
    description: string
  ): AgentEntity | null {
    const entity = this.getEntity(entityId);
    if (!entity || !this.descriptionOverrides) {
      return null;
    }

    this.descriptionOverrides.setDescription(entity.key, description);
    this.refresh();
    return this.getEntity(entityId);
  }

  /** Remove the human override and reveal each group's latest Agent prose. */
  public resetManualDescription(entityId: string): AgentEntity | null {
    const entity = this.getEntity(entityId);
    if (!entity || !this.descriptionOverrides) {
      return null;
    }

    this.descriptionOverrides.deleteDescription(entity.key);
    this.refresh();
    return this.getEntity(entityId);
  }

  public listRelations(filters?: {
    verb?: RelationVerb;
    sourceEntityId?: string;
    targetEntityId?: string;
  }): AgentRelation[] {
    return this.load().relations.filter((relation) => {
      if (filters?.verb && relation.verb !== filters.verb) {
        return false;
      }
      if (
        filters?.sourceEntityId &&
        relation.sourceEntityId !== filters.sourceEntityId
      ) {
        return false;
      }
      if (
        filters?.targetEntityId &&
        relation.targetEntityId !== filters.targetEntityId
      ) {
        return false;
      }
      return true;
    });
  }

  public getRelationsByEntity(
    entityId: string,
    direction?: 'outgoing' | 'incoming'
  ): AgentRelation[] {
    return this.load().relations.filter((relation) => {
      if (direction === 'outgoing') {
        return relation.sourceEntityId === entityId;
      }
      if (direction === 'incoming') {
        return relation.targetEntityId === entityId;
      }
      return (
        relation.sourceEntityId === entityId ||
        relation.targetEntityId === entityId
      );
    });
  }

  public getStats(): AgentGraphStats {
    const snapshot = this.load();
    return {
      groupCount: snapshot.groups.length,
      entityCount: snapshot.entities.length,
      relationCount: snapshot.relations.length,
      generatedAt: snapshot.generatedAt,
      scope: snapshot.scope,
      groups: snapshot.groups.map((group) => ({
        key: group.key,
        name: group.name,
        kind: group.kind,
        order: group.order,
        entityCount: group.entities.length,
        relationCount: group.relations.length,
      })),
    };
  }

  private load(): AgentGraphSnapshot {
    if (!fs.existsSync(this.graphPath)) {
      this.cachedSignature = 'missing';
      this.cachedSnapshot = EMPTY_SNAPSHOT;
      this.lastError = undefined;
      return this.cachedSnapshot;
    }

    let signature = '';
    try {
      const stat = fs.statSync(this.graphPath);
      signature = `${stat.mtimeMs}:${stat.size}`;
      if (signature === this.cachedSignature) {
        return this.cachedSnapshot;
      }

      const raw = fs.readFileSync(this.graphPath, 'utf8').replace(/^\uFEFF/, '');
      const document = parseAgentGraphDocument(JSON.parse(raw));
      this.cachedSnapshot = buildSnapshot(document, this.descriptionOverrides);
      this.cachedSignature = signature;
      this.lastError = undefined;
    } catch (error) {
      this.cachedSnapshot = EMPTY_SNAPSHOT;
      this.cachedSignature = signature;
      this.lastError = error instanceof Error ? error : new Error(String(error));
      console.error(`Failed to load generated graph at ${this.graphPath}:`, error);
    }

    return this.cachedSnapshot;
  }
}

/** Parse v2 manifests and normalize legacy v1 manifests into one framework group. */
export function parseAgentGraphDocument(value: unknown): AgentGraphDocument {
  if (!isRecord(value)) {
    throw new Error('Generated graph root must be an object');
  }
  const generatedAt = requireIsoTimestamp(value.generatedAt, 'generatedAt');
  const scope = optionalScope(value.scope, 'scope');

  if (value.version === 1) {
    const contents = parseGroupContents(
      value.entities,
      value.relations,
      'legacy framework group'
    );
    return {
      version: 2,
      generatedAt,
      scope,
      groups: [
        {
          key: 'framework',
          name: 'Framework',
          kind: 'framework',
          order: 0,
          scope,
          ...contents,
        },
      ],
    };
  }

  if (value.version !== 2) {
    throw new Error('Generated graph version must be 1 or 2');
  }
  if (!Array.isArray(value.groups) || value.groups.length === 0) {
    throw new Error('Generated graph groups must be a non-empty array');
  }

  const groupKeys = new Set<string>();
  const groupOrders = new Set<number>();
  const groups = value.groups.map((item, index) => {
    const group = parseGroup(item, index);
    if (groupKeys.has(group.key)) {
      throw new Error(`Duplicate generated graph group key: ${group.key}`);
    }
    if (groupOrders.has(group.order)) {
      throw new Error(`Duplicate generated graph group order: ${group.order}`);
    }
    groupKeys.add(group.key);
    groupOrders.add(group.order);
    return group;
  });

  const sortedGroups = [...groups].sort(
    (left, right) => left.order - right.order || left.name.localeCompare(right.name)
  );
  const frameworkGroups = sortedGroups.filter(
    (group) => group.kind === 'framework'
  );
  if (
    frameworkGroups.length !== 1 ||
    sortedGroups[0].kind !== 'framework' ||
    sortedGroups[0].key !== 'framework' ||
    sortedGroups[0].order !== 0
  ) {
    throw new Error(
      'Generated graph must start with exactly one framework group using key "framework" and order 0'
    );
  }

  return {
    version: 2,
    generatedAt,
    scope,
    groups: sortedGroups,
  };
}

function parseGroup(value: unknown, index: number): AgentGraphGroupInput {
  const label = `groups[${index}]`;
  if (!isRecord(value)) {
    throw new Error(`${label} must be an object`);
  }
  const key = requireString(value.key, `${label}.key`);
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(key)) {
    throw new Error(`${label}.key must use lowercase kebab-case`);
  }
  const name = requireString(value.name, `${label}.name`);
  if (!GROUP_KINDS.has(value.kind as AgentGraphGroupKind)) {
    throw new Error(`${label}.kind must be framework, module, or feature`);
  }
  if (!Number.isInteger(value.order) || (value.order as number) < 0) {
    throw new Error(`${label}.order must be a non-negative integer`);
  }
  const contents = parseGroupContents(value.entities, value.relations, label);
  return {
    key,
    name,
    kind: value.kind as AgentGraphGroupKind,
    order: value.order as number,
    description: optionalString(value.description, `${label}.description`),
    scope: optionalScope(value.scope, `${label}.scope`),
    ...contents,
  };
}

function parseGroupContents(
  entityValue: unknown,
  relationValue: unknown,
  label: string
): Pick<AgentGraphGroupInput, 'entities' | 'relations'> {
  if (!Array.isArray(entityValue) || !Array.isArray(relationValue)) {
    throw new Error(`${label} entities and relations must be arrays`);
  }

  const keys = new Set<string>();
  const entities = entityValue.map((item, index) => {
    const entity = parseEntity(item, `${label}.entities[${index}]`);
    if (keys.has(entity.key)) {
      throw new Error(`${label} has duplicate entity key: ${entity.key}`);
    }
    keys.add(entity.key);
    return entity;
  });

  const relationKeys = new Set<string>();
  const relations = relationValue.map((item, index) => {
    const relation = parseRelation(item, `${label}.relations[${index}]`);
    if (!keys.has(relation.source) || !keys.has(relation.target)) {
      throw new Error(
        `${label} relation ${index} references an unknown entity key`
      );
    }
    if (relation.source === relation.target) {
      throw new Error(`${label} relation ${index} must not be a self relation`);
    }
    const relationKey = `${relation.source}\u0000${relation.target}\u0000${relation.verb}`;
    if (relationKeys.has(relationKey)) {
      throw new Error(`${label} has a duplicate relation at index ${index}`);
    }
    relationKeys.add(relationKey);
    return relation;
  });

  return { entities, relations };
}

function parseEntity(value: unknown, label: string): AgentGraphEntityInput {
  if (!isRecord(value)) {
    throw new Error(`${label} must be an object`);
  }
  const key = requireString(value.key, `${label}.key`);
  const name = requireString(value.name, `${label}.name`);
  if (!ENTITY_TYPES.has(value.type as EntityType)) {
    throw new Error(`Unsupported entity type at ${label}.type`);
  }
  const filePath = requireString(value.filePath, `${label}.filePath`);
  validateRelativePath(filePath, `${label}.filePath`);
  const startLine = requirePositiveLine(value.startLine, `${label}.startLine`);
  const endLine = requirePositiveLine(value.endLine, `${label}.endLine`);
  if (endLine < startLine) {
    throw new Error(`${label}.endLine must be >= startLine`);
  }
  return {
    key,
    name,
    type: value.type as EntityType,
    filePath,
    startLine,
    endLine,
    description: optionalString(value.description, `${label}.description`),
  };
}

function parseRelation(
  value: unknown,
  label: string
): AgentGraphRelationInput {
  if (!isRecord(value)) {
    throw new Error(`${label} must be an object`);
  }
  const source = requireString(value.source, `${label}.source`);
  const target = requireString(value.target, `${label}.target`);
  if (!RELATION_VERBS.has(value.verb as RelationVerb)) {
    throw new Error(`Unsupported relation verb at ${label}.verb`);
  }
  if (!Array.isArray(value.evidence) || value.evidence.length === 0) {
    throw new Error(`${label}.evidence must not be empty`);
  }
  return {
    source,
    target,
    verb: value.verb as RelationVerb,
    description: optionalString(value.description, `${label}.description`),
    evidence: value.evidence.map((item, evidenceIndex) =>
      parseEvidence(item, `${label}.evidence[${evidenceIndex}]`)
    ),
  };
}

function parseEvidence(value: unknown, label: string): AgentGraphEvidence {
  if (!isRecord(value)) {
    throw new Error(`${label} must be an object`);
  }
  const filePath = requireString(value.filePath, `${label}.filePath`);
  validateRelativePath(filePath, `${label}.filePath`);
  const startLine = requirePositiveLine(value.startLine, `${label}.startLine`);
  const endLine =
    value.endLine === undefined
      ? undefined
      : requirePositiveLine(value.endLine, `${label}.endLine`);
  if (endLine !== undefined && endLine < startLine) {
    throw new Error(`${label}.endLine must be >= startLine`);
  }
  return {
    filePath,
    startLine,
    endLine,
    detail: optionalString(value.detail, `${label}.detail`),
  };
}

function buildSnapshot(
  document: AgentGraphDocument,
  descriptionOverrides?: AgentEntityDescriptionOverrideStore
): AgentGraphSnapshot {
  const timestamp = Date.parse(document.generatedAt);
  const groups = document.groups.map((group) => {
    const entityIds = new Map<string, string>();
    const entities: AgentEntity[] = group.entities.map((entity) => {
      const id = stableId('entity', `${group.key}\u0000${entity.key}`);
      const manualDescription = descriptionOverrides?.getDescription(entity.key);
      const hasManualDescription = manualDescription !== undefined;
      entityIds.set(entity.key, id);
      return {
        id,
        key: entity.key,
        groupKey: group.key,
        groupName: group.name,
        groupKind: group.kind,
        groupOrder: group.order,
        name: entity.name,
        type: entity.type,
        filePath: entity.filePath,
        startLine: entity.startLine,
        endLine: entity.endLine,
        description: hasManualDescription ? manualDescription : entity.description,
        createdAt: timestamp,
        updatedAt: timestamp,
        metadata: {
          source: 'agent-skill',
          agentKey: entity.key,
          scope: group.scope || document.scope || '.',
          groupKey: group.key,
          groupName: group.name,
          groupKind: group.kind,
          groupOrder: group.order,
          generatedDescription: entity.description,
          descriptionSource: hasManualDescription ? 'manual' : 'agent',
        },
      };
    });

    const relations: AgentRelation[] = group.relations.map((relation) => ({
      id: stableId(
        'relation',
        `${group.key}\u0000${relation.source}\u0000${relation.target}\u0000${relation.verb}`
      ),
      sourceKey: relation.source,
      targetKey: relation.target,
      groupKey: group.key,
      groupName: group.name,
      groupKind: group.kind,
      groupOrder: group.order,
      sourceEntityId: entityIds.get(relation.source)!,
      targetEntityId: entityIds.get(relation.target)!,
      verb: relation.verb,
      createdAt: timestamp,
      metadata: {
        source: 'agent-skill',
        scope: group.scope || document.scope || '.',
        groupKey: group.key,
        groupName: group.name,
        groupKind: group.kind,
        groupOrder: group.order,
        description: relation.description,
        evidence: relation.evidence,
      },
    }));

    return {
      key: group.key,
      name: group.name,
      kind: group.kind,
      order: group.order,
      description: group.description,
      scope: group.scope,
      entities,
      relations,
    };
  });

  return {
    generatedAt: document.generatedAt,
    scope: document.scope,
    groups,
    entities: groups.flatMap((group) => group.entities),
    relations: groups.flatMap((group) => group.relations),
  };
}

function stableId(kind: string, value: string): string {
  const digest = crypto
    .createHash('sha256')
    .update(`${kind}\u0000${value}`)
    .digest('hex')
    .slice(0, 24);
  return `agent-${kind}-${digest}`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function requireString(value: unknown, label: string): string {
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`${label} must be a non-empty string`);
  }
  return value;
}

function optionalString(value: unknown, label: string): string | undefined {
  if (value === undefined) {
    return undefined;
  }
  return requireString(value, label);
}

function requirePositiveLine(value: unknown, label: string): number {
  if (!Number.isInteger(value) || (value as number) < 1) {
    throw new Error(`${label} must be a positive integer`);
  }
  return value as number;
}

function requireIsoTimestamp(value: unknown, label: string): string {
  const timestamp = requireString(value, label);
  if (!isIsoTimestamp(timestamp)) {
    throw new Error(`${label} must be an ISO-8601 timestamp`);
  }
  return timestamp;
}

function optionalScope(value: unknown, label: string): string | undefined {
  if (value === undefined) {
    return undefined;
  }
  const scope = requireString(value, label);
  if (scope !== '.') {
    validateRelativePath(scope, label);
  }
  return scope;
}

function isIsoTimestamp(value: string): boolean {
  return (
    /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(value) &&
    !Number.isNaN(Date.parse(value))
  );
}

function validateRelativePath(value: unknown, label: string): void {
  const filePath = requireString(value, label);
  if (path.isAbsolute(filePath) || filePath.includes('\\')) {
    throw new Error(`${label} must be workspace-relative and use '/'`);
  }
  const segments = filePath.split('/');
  if (
    segments.some(
      (segment) => segment === '' || segment === '.' || segment === '..'
    )
  ) {
    throw new Error(`${label} contains an invalid path segment`);
  }
}
