import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { EntityFilters, EntityType, RelationVerb } from '../../utils/types';
import {
  AgentEntity,
  AgentGraphDocument,
  AgentGraphEntityInput,
  AgentGraphEvidence,
  AgentGraphRelationInput,
  AgentGraphSnapshot,
  AgentGraphStats,
  AgentRelation,
} from './types';

const ENTITY_TYPES = new Set<EntityType>([
  'function',
  'class',
  'interface',
  'variable',
  'file',
  'directory',
  'api',
  'config',
  'database',
  'service',
  'component',
  'external',
  'other',
]);

const RELATION_VERBS = new Set<RelationVerb>([
  'uses',
  'calls',
  'extends',
  'implements',
  'depends_on',
  'contains',
  'references',
  'imports',
  'exports',
]);

const EMPTY_SNAPSHOT: AgentGraphSnapshot = { entities: [], relations: [] };

/**
 * Reads the declarative graph generated by an Agent Skill.
 *
 * The manifest deliberately remains outside graph.sqlite. The extension uses
 * sql.js and saves the whole database file, so keeping Agent output in a
 * sidecar avoids concurrent writers silently overwriting each other.
 */
export class AgentGraphService {
  private readonly graphPath: string;
  private cachedSignature = '';
  private cachedSnapshot: AgentGraphSnapshot = EMPTY_SNAPSHOT;
  private lastError: Error | undefined;

  constructor(workspaceRoot: string) {
    this.graphPath = path.join(
      workspaceRoot,
      '.vscode',
      '.knowledge',
      'agent-graph.json'
    );
  }

  public getGraphPath(): string {
    return this.graphPath;
  }

  public getLastError(): Error | undefined {
    this.load();
    return this.lastError;
  }

  public refresh(): void {
    this.cachedSignature = '';
    this.load();
  }

  public getSnapshot(): AgentGraphSnapshot {
    return this.load();
  }

  public listEntities(filters?: EntityFilters): AgentEntity[] {
    return this.load().entities.filter((entity) => {
      if (filters?.type && entity.type !== filters.type) {
        return false;
      }
      if (filters?.filePath && entity.filePath !== filters.filePath) {
        return false;
      }
      if (
        filters?.name &&
        !entity.name.toLocaleLowerCase().includes(filters.name.toLocaleLowerCase())
      ) {
        return false;
      }
      return true;
    });
  }

  public getEntity(entityId: string): AgentEntity | null {
    return this.load().entities.find((entity) => entity.id === entityId) || null;
  }

  public listRelations(filters?: {
    verb?: RelationVerb;
    sourceEntityId?: string;
    targetEntityId?: string;
  }): AgentRelation[] {
    return this.load().relations.filter((relation) => {
      if (filters?.verb && relation.verb !== filters.verb) {
        return false;
      }
      if (
        filters?.sourceEntityId &&
        relation.sourceEntityId !== filters.sourceEntityId
      ) {
        return false;
      }
      if (
        filters?.targetEntityId &&
        relation.targetEntityId !== filters.targetEntityId
      ) {
        return false;
      }
      return true;
    });
  }

  public getRelationsByEntity(
    entityId: string,
    direction?: 'outgoing' | 'incoming'
  ): AgentRelation[] {
    return this.load().relations.filter((relation) => {
      if (direction === 'outgoing') {
        return relation.sourceEntityId === entityId;
      }
      if (direction === 'incoming') {
        return relation.targetEntityId === entityId;
      }
      return (
        relation.sourceEntityId === entityId ||
        relation.targetEntityId === entityId
      );
    });
  }

  public getStats(): AgentGraphStats {
    const snapshot = this.load();
    return {
      entityCount: snapshot.entities.length,
      relationCount: snapshot.relations.length,
      generatedAt: snapshot.generatedAt,
      scope: snapshot.scope,
    };
  }

  private load(): AgentGraphSnapshot {
    if (!fs.existsSync(this.graphPath)) {
      this.cachedSignature = 'missing';
      this.cachedSnapshot = EMPTY_SNAPSHOT;
      this.lastError = undefined;
      return this.cachedSnapshot;
    }

    let signature = '';
    try {
      const stat = fs.statSync(this.graphPath);
      signature = `${stat.mtimeMs}:${stat.size}`;
      if (signature === this.cachedSignature) {
        return this.cachedSnapshot;
      }

      const raw = fs.readFileSync(this.graphPath, 'utf8').replace(/^\uFEFF/, '');
      const document = parseAgentGraphDocument(JSON.parse(raw));
      this.cachedSnapshot = buildSnapshot(document);
      this.cachedSignature = signature;
      this.lastError = undefined;
    } catch (error) {
      this.cachedSnapshot = EMPTY_SNAPSHOT;
      this.cachedSignature = signature;
      this.lastError = error instanceof Error ? error : new Error(String(error));
      console.error(`Failed to load Agent Graph at ${this.graphPath}:`, error);
    }

    return this.cachedSnapshot;
  }
}

export function parseAgentGraphDocument(value: unknown): AgentGraphDocument {
  if (!isRecord(value)) {
    throw new Error('Agent Graph root must be an object');
  }
  if (value.version !== 1) {
    throw new Error('Agent Graph version must be 1');
  }
  if (
    typeof value.generatedAt !== 'string' ||
    !isIsoTimestamp(value.generatedAt)
  ) {
    throw new Error('Agent Graph generatedAt must be an ISO-8601 timestamp');
  }
  if (value.scope !== undefined) {
    if (value.scope !== '.') {
      validateRelativePath(value.scope, 'scope');
    }
  }
  if (!Array.isArray(value.entities) || !Array.isArray(value.relations)) {
    throw new Error('Agent Graph entities and relations must be arrays');
  }

  const keys = new Set<string>();
  const entities = value.entities.map((item, index) => {
    const entity = parseEntity(item, index);
    if (keys.has(entity.key)) {
      throw new Error(`Duplicate Agent Graph entity key: ${entity.key}`);
    }
    keys.add(entity.key);
    return entity;
  });

  const relationKeys = new Set<string>();
  const relations = value.relations.map((item, index) => {
    const relation = parseRelation(item, index);
    if (!keys.has(relation.source) || !keys.has(relation.target)) {
      throw new Error(
        `Agent Graph relation ${index} references an unknown entity key`
      );
    }
    if (relation.source === relation.target) {
      throw new Error(`Agent Graph relation ${index} must not be a self relation`);
    }
    const relationKey = `${relation.source}\u0000${relation.target}\u0000${relation.verb}`;
    if (relationKeys.has(relationKey)) {
      throw new Error(`Duplicate Agent Graph relation at index ${index}`);
    }
    relationKeys.add(relationKey);
    return relation;
  });

  return {
    version: 1,
    generatedAt: value.generatedAt,
    scope: value.scope as string | undefined,
    entities,
    relations,
  };
}

function parseEntity(value: unknown, index: number): AgentGraphEntityInput {
  if (!isRecord(value)) {
    throw new Error(`Agent Graph entity ${index} must be an object`);
  }
  const key = requireString(value.key, `entities[${index}].key`);
  const name = requireString(value.name, `entities[${index}].name`);
  if (!ENTITY_TYPES.has(value.type as EntityType)) {
    throw new Error(`Unsupported entity type at entities[${index}].type`);
  }
  const filePath = requireString(value.filePath, `entities[${index}].filePath`);
  validateRelativePath(filePath, `entities[${index}].filePath`);
  const startLine = requirePositiveLine(
    value.startLine,
    `entities[${index}].startLine`
  );
  const endLine = requirePositiveLine(value.endLine, `entities[${index}].endLine`);
  if (endLine < startLine) {
    throw new Error(`entities[${index}].endLine must be >= startLine`);
  }
  const description = optionalString(
    value.description,
    `entities[${index}].description`
  );
  return {
    key,
    name,
    type: value.type as EntityType,
    filePath,
    startLine,
    endLine,
    description,
  };
}

function parseRelation(value: unknown, index: number): AgentGraphRelationInput {
  if (!isRecord(value)) {
    throw new Error(`Agent Graph relation ${index} must be an object`);
  }
  const source = requireString(value.source, `relations[${index}].source`);
  const target = requireString(value.target, `relations[${index}].target`);
  if (!RELATION_VERBS.has(value.verb as RelationVerb)) {
    throw new Error(`Unsupported relation verb at relations[${index}].verb`);
  }
  if (!Array.isArray(value.evidence) || value.evidence.length === 0) {
    throw new Error(`relations[${index}].evidence must not be empty`);
  }
  return {
    source,
    target,
    verb: value.verb as RelationVerb,
    description: optionalString(
      value.description,
      `relations[${index}].description`
    ),
    evidence: value.evidence.map((item, evidenceIndex) =>
      parseEvidence(item, index, evidenceIndex)
    ),
  };
}

function parseEvidence(
  value: unknown,
  relationIndex: number,
  evidenceIndex: number
): AgentGraphEvidence {
  const label = `relations[${relationIndex}].evidence[${evidenceIndex}]`;
  if (!isRecord(value)) {
    throw new Error(`${label} must be an object`);
  }
  const filePath = requireString(value.filePath, `${label}.filePath`);
  validateRelativePath(filePath, `${label}.filePath`);
  const startLine = requirePositiveLine(value.startLine, `${label}.startLine`);
  const endLine =
    value.endLine === undefined
      ? undefined
      : requirePositiveLine(value.endLine, `${label}.endLine`);
  if (endLine !== undefined && endLine < startLine) {
    throw new Error(`${label}.endLine must be >= startLine`);
  }
  return {
    filePath,
    startLine,
    endLine,
    detail: optionalString(value.detail, `${label}.detail`),
  };
}

function buildSnapshot(document: AgentGraphDocument): AgentGraphSnapshot {
  const timestamp = Date.parse(document.generatedAt);
  const entityIds = new Map<string, string>();
  const entities: AgentEntity[] = document.entities.map((entity) => {
    const id = stableId('entity', entity.key);
    entityIds.set(entity.key, id);
    return {
      id,
      key: entity.key,
      name: entity.name,
      type: entity.type,
      filePath: entity.filePath,
      startLine: entity.startLine,
      endLine: entity.endLine,
      description: entity.description,
      createdAt: timestamp,
      updatedAt: timestamp,
      metadata: {
        source: 'agent-skill',
        agentKey: entity.key,
        scope: document.scope || '.',
      },
    };
  });

  const relations: AgentRelation[] = document.relations.map((relation) => ({
    id: stableId('relation', `${relation.source}\u0000${relation.target}\u0000${relation.verb}`),
    sourceKey: relation.source,
    targetKey: relation.target,
    sourceEntityId: entityIds.get(relation.source)!,
    targetEntityId: entityIds.get(relation.target)!,
    verb: relation.verb,
    createdAt: timestamp,
    metadata: {
      source: 'agent-skill',
      scope: document.scope || '.',
      description: relation.description,
      evidence: relation.evidence,
    },
  }));

  return {
    generatedAt: document.generatedAt,
    scope: document.scope,
    entities,
    relations,
  };
}

function stableId(kind: string, value: string): string {
  const digest = crypto
    .createHash('sha256')
    .update(`${kind}\u0000${value}`)
    .digest('hex')
    .slice(0, 24);
  return `agent-${kind}-${digest}`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function requireString(value: unknown, label: string): string {
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`${label} must be a non-empty string`);
  }
  return value;
}

function optionalString(value: unknown, label: string): string | undefined {
  if (value === undefined) {
    return undefined;
  }
  return requireString(value, label);
}

function requirePositiveLine(value: unknown, label: string): number {
  if (!Number.isInteger(value) || (value as number) < 1) {
    throw new Error(`${label} must be a positive integer`);
  }
  return value as number;
}

function isIsoTimestamp(value: string): boolean {
  return (
    /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(value) &&
    !Number.isNaN(Date.parse(value))
  );
}

function validateRelativePath(value: unknown, label: string): void {
  const filePath = requireString(value, label);
  if (path.isAbsolute(filePath) || filePath.includes('\\')) {
    throw new Error(`${label} must be workspace-relative and use '/'`);
  }
  const segments = filePath.split('/');
  if (
    segments.some(
      (segment) => segment === '' || segment === '.' || segment === '..'
    )
  ) {
    throw new Error(`${label} contains an invalid path segment`);
  }
}
