import { describe, expect, it, vi } from 'vitest';
import type {
  KnowledgeEntity,
  KnowledgeRelation,
} from '../services/knowledgeGraphService';
import { buildKnowledgeCodeLensModels } from './knowledgeCodeLensModel';

describe('buildKnowledgeCodeLensModels', () => {
  it('shows Agent descriptions and unified graph statistics', () => {
    const agentEntity = entity({
      id: 'agent-a',
      name: 'AgentService',
      description: '  Generated by the Agent\nfrom source evidence.  ',
      origin: 'agent',
    });
    const manualEntity = entity({
      id: 'manual-b',
      name: 'ManualService',
      description: 'Human description',
      origin: 'manual',
      startLine: 20,
    });
    const relations: KnowledgeRelation[] = [
      {
        id: 'relation-a-b',
        sourceEntityId: agentEntity.id,
        targetEntityId: manualEntity.id,
        verb: 'depends_on',
        createdAt: 1,
        origin: 'agent',
      },
    ];
    const getObservationCount = vi.fn((id: string) =>
      id === manualEntity.id ? 2 : 0
    );

    const models = buildKnowledgeCodeLensModels(
      [agentEntity, manualEntity],
      relations,
      100,
      getObservationCount
    );

    expect(models).toEqual([
      {
        entityId: 'agent-a',
        line: 9,
        title: '🧠 KG: Generated by the Agent from source evidence. · 📝 0 · 🔗 1',
      },
      {
        entityId: 'manual-b',
        line: 19,
        title: '🧠 KG: Human description · 📝 2 · 🔗 1',
      },
    ]);
  });

  it('falls back to the entity name and skips out-of-range locations', () => {
    const visible = entity({ description: '', origin: 'agent' });
    const outside = entity({
      id: 'outside',
      description: 'Outside',
      origin: 'agent',
      startLine: 101,
    });

    expect(
      buildKnowledgeCodeLensModels([visible, outside], [], 100, () => 0)
    ).toEqual([
      {
        entityId: visible.id,
        line: 9,
        title: '🧠 KG: Service · 📝 0 · 🔗 0',
      },
    ]);
  });
});

function entity(
  overrides: Partial<KnowledgeEntity> & Pick<KnowledgeEntity, 'origin'>
): KnowledgeEntity {
  return {
    id: 'entity-a',
    name: 'Service',
    type: 'service',
    filePath: 'src/service.ts',
    startLine: 10,
    endLine: 30,
    createdAt: 1,
    updatedAt: 1,
    ...overrides,
  };
}
